#! /bin/bash
# Author: chenkaiyao <chenkaiyao@molmc.com>

# ATOM 版本号
PRODUCT_VERSION_STRING_ATOM=3.6.6.0

# NEUTRON 版本号
PRODUCT_VERSION_STRING_NEUTRON=2.0.2.3

# NUT 版本号
PRODUCT_VERSION_STRING_NUT=1.0.3.3

# FIG 版本号
PRODUCT_VERSION_STRING_FIG=1.0.2.2

# FOX 版本号
PRODUCT_VERSION_STRING_FOX=1.0.1.1

# ANT 版本号
PRODUCT_VERSION_STRING_ANT=1.0.0.1

# W67 版本号
PRODUCT_VERSION_STRING_W67=1.0.2.2

# W323 版本号
PRODUCT_VERSION_STRING_W323=1.0.2.2

# L6 版本号
PRODUCT_VERSION_STRING_L6=1.0.0.1

